### ISSUE TITLE
error loading the plugin on 1.18

### ISSUE THREAD

**Issue by Paceski** [GC-spigot/AdvancedTrades#14]
### Describe the bug

the plugin is failing to load on my 1.18 server

### How to reproduce

plugin not loading

### Server Log

https://mcpaste.io/68e7fda764555a18

**Comment by Paceski** [comment]
:)

**Comment by MrDraqon** [comment]
9 days and still not fixed, legit just an NBTAPI issue just update it and push an update so we can use :/ its a plugin breaking issue it should be fixed asap. atleast reply to issues so we know theres someone who cares 👎

**Comment by Paceski** [comment]
Amazing support, might be expecting a refund soon
