### ISSUE TITLE
Trade enchant lost

### ISSUE THREAD

**Issue by ImYenil** [GC-spigot/AdvancedTrades#4]
### Describe the bug

I'm using the default config, but when I use commandTrade, the enchantments on the sword disappear after trading. Is it normal?

### How to reproduce

When i use commandTrade

### Screenshots / Videos

X

### Server Log

X

**Comment by GC-spigot** [comment]
You add enchants to the reward command. The displayed item is just for display. 

How else would you show off what a command gives?

**Comment by ImYenil** [comment]
> You add enchants to the reward command. The displayed item is just for display. How else would you show off what a command gives?
> […](#)
> On 2021-11-04, at 01:34 AM, chochoco4777 ***@***.***> wrote: ﻿ Describe the bug I'm using the default config, but when I use commandTrade, the enchantments on the sword disappear after trading. Is it normal? How to reproduce When i use commandTrade Screenshots / Videos X Server Log X — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

i solved.
