### ISSUE TITLE
Villagers disappear

### ISSUE THREAD

**Issue by 0pGam3rMC** [GC-spigot/AdvancedTrades#5]
The villagers i spawn seem to disappear after some time..is there any way to keep that from happening?

**Comment by ghost** [comment]
Same here, I keep my villagers in the spawn chunks. They were there for around a week for me and then after a restart they all disappear, I hope whatever is causing this gets fixed soon.

**Comment by GC-spigot** [comment]
Villagers normally do not despawn unless they are removed by plugins. We don't interact with entities, remove / keep them. However I'll keep this in mind for further updates :)
