### ISSUE TITLE
RequierdProfession not working correctly

### ISSUE THREAD

**Issue by Dalsok** [GC-spigot/AdvancedTrades#6]
### Describe the bug
paperspigot 1.18.1
Advanced trades 1.0.7
Villagertrades do not work when setting a professionrequirment in the trades.yml

### How to reproduce

try to set a professionrequierment

### Screenshots / Videos
My setup for the trade
https://pastebin.com/pYG86Rdt

**Comment by GC-spigot** [comment]
Fixed
